# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/Data_visualization',
                'doc_host': 'https://Kkhurana007.github.io',
                'git_url': 'https://github.com/Kkhurana007/Data_visualization',
                'lib_path': 'Data_visualization'},
  'syms': {'Data_visualization.core': {'Data_visualization.core.foo': ('core.html#foo', 'Data_visualization/core.py')}}}
